server:
  port: 7070

spring:
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 127.0.0.1
    password: 1747
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/gundam?serverTimezone=Asia/Seoul
    password: 1747
  jpa:
    hibernate:
      ddl-Auto: create-drop #update 하면 변경만함, 저장함 반대는 create-drop
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  mvc:
    converters:
      preferred-json-mapper: gson
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 278e1aba293a475c4292
            client-secret: 8141e7f9d8fd64725d3a89736165ebda208f9222
            redirectUri: http://localhost:7070/auth/github/callback
            scope: repo, user


logging:
  level:
    root: info
  file:
    name: log/app.log
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}-%i.log
      max-file-size: 1MB

jwt:
  secret-key: ihatejavascriptihatevuefuckyoujavascriptfuckyouvuefreehongkong
  access-token-expiration-sec: 1800
  refresh-token-expiration-sec: 1209600

mail:
  address:
    admin: ssafy@ssafy.com